"""campo imagem

Revision ID: 317e0006f693
Revises: 26b7071ccff9
Create Date: 2026-05-21 16:02:29.514738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317e0006f693'
down_revision = '26b7071ccff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leilao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leilao', schema=None) as batch_op:
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###
